assets:
  dropboxAPIKey.txt: driver733/VKMusicUploaderConfig/dropboxAPIKey.txt
architect:
  - driver733
docker:
  image: "maven:3.5-jdk-8"
install: |-
  wget "http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar"
  mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar
merge:
  commanders:
  - driver733
  fast-forward: default
  rebase: true
  script:
#    Before
#    |-
    - mvn clean
    - "curl \"https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh\" -o dropbox_uploader.sh"
    - chmod +x dropbox_uploader.sh
    - ./dropbox_uploader.sh | cat dropboxAPIKey.txt
    - M2="/root/.m2"
    - ./dropbox_uploader.sh download m2.zip /m2.zip
    - unzip m2.zip -d ${M2}
    - md5deep -r -s ${M2} > m2sumOld
#    Build
    - mvn clean install -Pqulice
#    After
    - NEW="$(md5deep -r -x m2sumOld ${M2})"
    - echo NEW
#    if [ "${NEW}" != "" ]; then
#    	echo m2 has changed since last build
#    	echo archiving m2...
#    	zip -r m2.zip ${M2}
#    	echo uploading m2 archive...
#    	./dropbox_uploader.sh upload m2.zip /m2.zip
#    else
#    	echo m2 has NOT changed since last build
#    fi
    