assets:
  dropboxAPIKey.txt: "driver733/VKMusicUploaderConfig#dropboxAPIKey.txt"
#env:
#  M2: "/root/.m2"

architect:
  - driver733
docker:
  image: "maven:3.5-jdk-8"
#install: |-
#  wget "http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar"
#  mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar
merge:
  commanders:
  - driver733
  fast-forward: default
  rebase: true
  script:
  #    Before
#      - "mvn clean"
      - "curl \"https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh\" -o dropbox_uploader.sh"
      - "chmod +x dropbox_uploader.sh"
      - "./dropbox_uploader.sh | cat /home/r/dropboxAPIKey.txt"
#      - "M2=\"/root/.m2\""
      - "./dropbox_uploader.sh download m2.zip /m2.zip"
      - "unzip m2.zip -d /root/.m2"
      - "md5deep -r -s /root/.m2 > m2sumOld"
      - "wget \"http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar\""
      - "mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar"
  #    Build
      - "mvn clean install -Pqulice"
  #    After
#      - "NEW=\"$(md5deep -r -x m2sumOld /root/.m2)\""
#      - "echo NEW"
      - "if [ \"$(md5deep -r -x m2sumOld /root/.m2)\" != \"\" ]; then zip -r m2.zip /root/.m2; ./dropbox_uploader.sh upload m2.zip /m2.zip; fi"

    