assets:
  dropboxAPIKey.txt: "driver733/VKMusicUploaderConfig#dropboxAPIKey.txt"
  userId.txt: "driver733/VKMusicUploaderConfig#userId.txt"
  groupId.txt: "driver733/VKMusicUploaderConfig#groupId.txt"
  token.txt: "driver733/VKMusicUploaderConfig#token.txt"
architect:
  - driver733
docker:
  as_root: true
  image: "maven:3.5-jdk-8"
#install: |-
#  wget "http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar"
#  mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar
merge:
  commanders:
  - driver733
  fast-forward: default
  rebase: true
  script:
      - apt-get update
      - apt-get -y upgrade
      - apt-get -y install md5deep
      - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
      - chmod +x dropbox_uploader.sh
      # - "cat /home/r/dropboxAPIKey.txt > cmds.txt; echo -e \"\ny\" >> /home/r/cmds.txt; ./dropbox_uploader.sh < cmds.txt"
      - ./dropbox_uploader.sh < /home/r/dropboxAPIKey.txt
      - ./dropbox_uploader.sh download m2.tar.gz m2.tar.gz
      - tar -xzvf m2.tar.gz -C / > /dev/null
      - md5deep -r -s /root/.m2 > m2sumOld
      # VK SDK fork
      - wget "http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar"
      - mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar
      # User ID, group ID and token params for integration tests
      # Build
      - mvn clean install verify -DuserId=`cat /home/r/userId.txt` -DgroupId=`cat /home/r/groupId.txt` -Dtoken=`cat /home/r/token.txt` -Pqulice
      # Upload (if necessary) updated archive to dropbox
      - if [ "$(md5deep -r -x m2sumOld /root/.m2 | grep -v --ignore-case -e "driver733" -e "VKMusicUploader")" != "" ]; then tar -czvf m2.tar.gz /root/.m2 > /dev/null; ./dropbox_uploader.sh upload m2.tar.gz /m2.tar.gz; fi
release:
  pre: false
