assets:
  dropboxAPIKey.txt: "driver733/VK-Uploader-Config#dropboxAPIKey.txt"
  credentials.properties: "driver733/VK-Uploader-Config#credentials.properties"
  secring.gpg: "driver733/VK-Uploader-Config#secring.gpg"
  pubring.gpg: "driver733/VK-Uploader-Config#pubring.gpg"
  settings.xml: "driver733/VK-Uploader-Config#settings.xml"
architect:
- driver733
docker:
  as_root: true
  image: "maven:3.5-jdk-8"
merge:
  commanders:
    - driver733
  fast-forward: default
  rebase: true
  script: |-
    apt-get update
    apt-get -y upgrade
    apt-get -y install md5deep
    curl "https://raw.githubusercontent.com/driver733/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
    chmod +x dropbox_uploader.sh
    ./dropbox_uploader.sh < /home/r/dropboxAPIKey.txt
    ./dropbox_uploader.sh download m2.tar.gz m2.tar.gz
    tar -xzvf m2.tar.gz -C / > /dev/null
    md5deep -r -s /root/.m2 > m2sumOld
    PROPS="/home/r/credentials.properties"
    mvn clean verify jacoco:report coveralls:report qulice:check -Dvk.userId=`cat $PROPS | grep "vk.user"  | cut -d'=' -f2` -Dvk.groupId=`cat $PROPS | grep "vk.group" | cut -d'=' -f2` -Dvk.token=`cat $PROPS | grep "vk.token" | cut -d'=' -f2` -Dcoveralls.repo.token=`cat $PROPS | grep "coveralls.repo.token" | cut -d'=' -f2`
    if [ "$(md5deep -r -x m2sumOld /root/.m2 | grep -v --ignore-case -e "driver733" -e "VK-Uploader")" != "" ]; then tar -czvf m2.tar.gz /root/.m2 > /dev/null; ./dropbox_uploader.sh upload m2.tar.gz /m2.tar.gz; fi
release:
  script: |-
    apt-get update
    apt-get -y upgrade
    apt-get -y install md5deep
    curl "https://raw.githubusercontent.com/driver733/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
    chmod +x dropbox_uploader.sh
    ./dropbox_uploader.sh < /home/r/dropboxAPIKey.txt
    ./dropbox_uploader.sh download m2.tar.gz m2.tar.gz
    tar -xzvf m2.tar.gz -C / > /dev/null
    md5deep -r -s /root/.m2 > m2sumOld
    if [ "$(md5deep -r -x m2sumOld /root/.m2 | grep -v --ignore-case -e "driver733" -e "VK-Uploader")" != "" ]; then tar -czvf m2.tar.gz /root/.m2 > /dev/null; ./dropbox_uploader.sh upload m2.tar.gz /m2.tar.gz; fi
    PROPS="/home/r/credentials.properties"
    mvn versions:set "-DnewVersion=${tag}" -e
    git commit -am "${tag}"
    mvn clean deploy jacoco:report coveralls:report qulice:check --settings /home/r/settings.xml -Dvk.userId=`cat $PROPS | grep "vk.user"  | cut -d'=' -f2` -Dvk.groupId=`cat $PROPS | grep "vk.group" | cut -d'=' -f2` -Dvk.token=`cat $PROPS | grep "vk.token" | cut -d'=' -f2` -Dcoveralls.repo.token=`cat $PROPS | grep "coveralls.repo.token" | cut -d'=' -f2`