assets:
  dropboxAPIKey.txt: "driver733/VKUploaderConfig#dropboxAPIKey.txt"
  credentials.properties: "driver733/VKUploaderConfig#credentials.properties"
architect:
  - driver733
docker:
  as_root: true
  image: "maven:3.5-jdk-8"
#install: |-
#  wget "http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar"
#  mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar
merge:
  commanders:
  - driver733
  fast-forward: default
  rebase: true
  script:
      - apt-get update
      - apt-get -y upgrade
      - apt-get -y install md5deep
      - # .m2 archive
      - curl "https://raw.githubusercontent.com/driver733/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
      - chmod +x dropbox_uploader.sh
      - ./dropbox_uploader.sh < /home/r/dropboxAPIKey.txt
      - ./dropbox_uploader.sh download m2.tar.gz m2.tar.gz
      - tar -xzvf m2.tar.gz -C / > /dev/null
      - md5deep -r -s /root/.m2 > m2sumOld
      # VK SDK fork
      - wget "http://jitpack.io/com/github/driver733/vk-java-sdk/547a05fa42/vk-java-sdk-547a05fa42.jar"
      - mvn install:install-file -Dfile=vk-java-sdk-547a05fa42.jar -DgroupId=com.github.driver733 -DartifactId=vk-java-sdk -Dversion=547a05fa42 -Dpackaging=jar
      # Build
      - PROPS="/home/r/credentials.properties"
#      - USER=`cat $PROPS | grep "vk.user"  | cut -d'=' -f2`
#      - GROUP=`cat $PROPS | grep "vk.group" | cut -d'=' -f2`
#      - TOKEN=`cat $PROPS | grep "vk.token" | cut -d'=' -f2`
      - mvn clean verify jacoco:report coveralls:report clean verify -Dvk.userId=`cat $PROPS | grep "vk.user"  | cut -d'=' -f2` -Dvk.groupId=`cat $PROPS | grep "vk.group" | cut -d'=' -f2` -Dvk.token=`cat $PROPS | grep "vk.token" | cut -d'=' -f2` -Dcoveralls.repo.token=`cat $PROPS | grep "coveralls.repo.token" | cut -d'=' -f2`
      # Upload (if necessary) the updated .m2 archive to Dropbox
      - if [ "$(md5deep -r -x m2sumOld /root/.m2 | grep -v --ignore-case -e "driver733" -e "VKMusicUploader")" != "" ]; then tar -czvf m2.tar.gz /root/.m2 > /dev/null; ./dropbox_uploader.sh upload m2.tar.gz /m2.tar.gz; fi
release:
  pre: false
