language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
script:
  - set -e
  - mvn clean
  - pdd --source=$(pwd) --file=/dev/null
  - mvn clean test qulice:check -DskipITs --errors --batch-mode
before_install:
  - rvm install 2.2.2
  - rvm use 2.2.2
install:
  - gem install pdd
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
notifications:
  email: false
  slack: false
